# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: make runserver
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
